# Generated by Django 4.2 on 2023-04-13 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto_Salon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releasedate',
            name='releasedate',
            field=models.IntegerField(verbose_name='Дата выпуска'),
        ),
        migrations.CreateModel(
            name='Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('specifications', models.TextField(max_length=200, verbose_name='Характеристики')),
                ('color', models.CharField(max_length=30, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.car', verbose_name='Машина')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.country', verbose_name='Страна')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.fuel', verbose_name='Топливо')),
                ('releasedate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.releasedate', verbose_name='Дата выпуска')),
                ('stamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.stamp', verbose_name='Модель')),
                ('typeofcar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto_Salon.typeofcar', verbose_name='Типы автомобилей')),
            ],
        ),
    ]
