# Generated by Django 3.2 on 2023-04-18 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto_Salon', '0002_alter_releasedate_releasedate_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='create',
            options={'ordering': ['car'], 'verbose_name': 'Создание манины', 'verbose_name_plural': 'Создание машиней'},
        ),
    ]
